baseURL = "http://jeremystevens.net/"
languageCode = "en-us"
title = "Home"
publishDir = "public"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # probably adjust upwards?
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "A place for my dabblings"
  facebook = ""
  twitter = "https://twitter.com/NinjaJez"
  instagram = ""
  youtube = ""
  github = "https://github.com/Ninjars"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jezstevens/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/sheep-stare.jpg"
  recent_posts_number = 4
  mainSections=["posts","projects"]
